ORFs=["ORF6", "ORF8", "ORF10", "ORF17", "ORF21", "ORF23", "ORF24"]

rule all:
    input:
        expand("blastp_proteins/{ORF}_blastp_proteins.faa", ORF = ORFs)

rule iterative_blastp:
    conda: "diamond"
    input: "initial_proteins/{ORF}_initial_proteins.faa"
    output: "blastp_proteins/{ORF}_blastp_proteins.faa"
    resources:
        mem="50GB",
        threads=16,
        time="10-10:00:00",
        partition="CLUSTER"
    params: 
        db="/bioinf/home/dlueckin/dbs/diamond_nr/nr.dmnd",
        # db="initial_proteins/test.dmnd",
        evalue=0.00001,
        bitscore=50
    log:
        "log/{ORF}_test.log"
    shell:
        """
        python3 scripts/01_iterative_blast.py \
        {input} {output} --db {params.db} \
        --evalue {params.evalue} \
        --bitscore {params.bitscore} 
        """

rule iterative_blastp_ASL:
    conda: "diamond"
    input: "blastp_proteins/{ORF}_blastp_proteins.faa"
    output: "blastp_proteins/{ORF}_blastp_proteins.faa"

