# author: dlueckin
# date: Wed Aug 30 12:09:04 2023

# libraries ---------------------------------------------------------------
library(data.table)
library(stringr)
library(seqinr)
library(tidyr)
library(ggplot2)
library(dplyr)
library(rentrez)

# working directory -------------------------------------------------------
this_dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this_dir)
print(paste0("Setting wd to: \n ", this_dir))


# set up constants --------------------------------------------------------

# DONT LOOK HERE!
# CHECK THE DATAFRAME GENERATED BY 
# "do_the_core_genes_occur_alone_in_nr/03_analysis.R"
# this tells you everything
# we filtered for bitscore 50 
# this is based on hmms

prot_df <- fread("../do_the_core_genes_occur_alone_in_nr/filtered_prot_df.tsv")

non_halo <- prot_df %>% 
    filter(!str_detect(string = organism_name, pattern = regex("halo", ignore_case = T)))

fwrite(non_halo, "non_halo_hits.tsv")





# test blastp level -------------------------------------------------------

df <- data.table()

for(file in list.files("../../A_generate_protein_clusters/02_blastp_results/")){
    tmp_df <- fread(paste0("../../A_generate_protein_clusters/02_blastp_results/", file))
    names(tmp_df) <- unlist(str_split("qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore", " "))
    tmp_df$ORF <- str_remove(file, "\\_it.*$")
    
    df <- rbind(df, tmp_df)
}

df$aln_length <- df$send - df$sstart



# exclude proteins we have already in our models --------------------------

known_proteins <- ""
for(file in list.files("../../A_generate_protein_clusters/FINAL_proteins/")){
    seq_names <- unlist(getName(read.fasta(paste0("../../A_generate_protein_clusters/FINAL_proteins/", file))))
    
    known_proteins <- c(known_proteins, seq_names)
    
}

novel_df <- df %>% 
    filter(!sseqid %in% known_proteins)

unique_novel_df <- novel_df %>% 
    group_by(sseqid) %>% 
    slice_max(n = 1, order_by =  aln_length) %>% 
    distinct()


# add acc and organism name -----------------------------------------------

unique_novel_df$organism_acc <- NA
unique_novel_df$organism_name <- NA

# Specify your email address for the Entrez API
email <- "dom.luecking@gmail.com"
API_KEY = "ed38a68e4cac02507e4bc585e8913bab5a08"
MAX_ITERATION = 5

# function to retrieve the ID and org name
getOrganismAndNuccoreAcc <- function(acc){
    # Use tryCatch to handle errors
    tryCatch({
        # use entrez link to find the protein_nuccore link
        link_result <- entrez_link(dbfrom = "protein", id = acc, db = "all", api_key = API_KEY)
        Sys.sleep(0.1)        
        
        protein_nuc <- link_result$links["protein_nuccore"]
        
        # catcht the weird entrez results
        if(is.null(protein_nuc)){
            protein_nuc <- unlist(link_result[[1]]$links["protein_nuccore"])
        }
        if(is.list(protein_nuc)){
            protein_nuc <- unlist(protein_nuc)[1]
        }
        
        # Use entrez_summary() to retrieve the summary for the protein accession
        summary_result <- entrez_summary(db="nuccore", id = protein_nuc,  api_key = API_KEY)
        Sys.sleep(0.1)
        
        # Extract the organism name from the summary_result
        org_name <- paste0(summary_result$organism, "_", summary_result$strain)
        org_acc <- summary_result$caption
        
        # return the organism name
        return(paste0(org_name, "____", org_acc))
        
    }, error = function(e) {
        # If an error occurs, return "NA"
        return(NA)
    })
    
}


j = 1
while(j <= MAX_ITERATION){
    for(i in 1:nrow(unique_novel_df)){
        if(is.na(unique_novel_df$organism_acc[i])){
            Name_and_Acc <- getOrganismAndNuccoreAcc(unique_novel_df$sseqid[i])
            organism_name <- str_remove(Name_and_Acc, "\\_\\_\\_\\_.*$")
            organism_acc <- str_remove(Name_and_Acc, "^.*\\_\\_\\_\\_")
            
            unique_novel_df$organism_name[i] <- organism_name
            unique_novel_df$organism_acc[i] <- organism_acc
            
        }
    }
    print(paste0("iteration: ", j))
    j <- j + 1
}






